### ISSUE TITLE
New pypi release

### ISSUE THREAD

**Issue by Evidlo** [dfm/kplr#32]
I see that the python3 async issue was fixed in https://github.com/dfm/kplr/issues/27

Could we get a new pypi release with these changes?

**Comment by dfm** [comment]
Should be available now.

That being said, this project probably isn't the best thing to use anymore. Instead I would use

- [lightkurve](https://docs.lightkurve.org/) to download light curves, and
- [astroquery](https://astroquery.readthedocs.io/en/latest/nasa_exoplanet_archive/nasa_exoplanet_archive.html) to query catalogs

**Comment by Evidlo** [comment]
Thanks for the response.  It might be helpful to others to include those alternative projects at the top of the README.
